name: "TemperaturePlugin"
version: "${project.version}"
main: "top.cmarco.temperatureplugin.TemperaturePlugin"
api-version: '1.17'
folia-supported: false
authors: ["CMarco"]
description: "The Most Realistic Temperature Plugin Ever Created!"
softdepend: ["PlaceholderAPI"]
commands:
  temperature:
    description: 'Manage your temperature in-game.'
